export const CREATE_PLAYER = "CREATE_PLAYER";
export const CREATE_PLAYER_SUCCES = "CREATE_PLAYER_SUCCES";
export const CREATE_PLAYER_FAILURE = "CREATE_PLAYER_FAILURE";

export const LOADIND_PLAYERS = "LOADIND_PLAYERS";
export const PLAYERS_LOAD_SUCCES = "PLAYERS_LOAD_SUCCES";
export const GET_PLAYERS_FAILURE = "GET_PLAYERS_FAILURE";

