//#region ------- DRIVER --------
export const TYPES_CREATE_DRIVER = {
    CREATE_DRIVER: "CREATE_DRIVER",
    CREATE_DRIVER_SUCCESS: "CREATE_DRIVER_SUCCESS",
    CREATE_DRIVER_FAILURE: "CREATE_DRIVE_FAILURE"
}

export const TYPES_LOAD_DRIVERS = {
  LOADING_DRIVERS: "LOADING_DRIVERS",
  LOAD_DRIVERS_SUCCESS: "LOAD_DRIVERS_SUCCESS",
  LOAD_DRIVERS_FAILURE: "LOAD_DRIVERS_FAILURE",
}
//#endregion

//#region ------- TRACK --------
export const TYPES_CREATE_TRACK = {
  CREATE_TRACK: "CREATE_TRACK",
  CREATE_TRACK_SUCCESS: "CREATE_TRACK_SUCCESS",
  CREATE_TRACK_FAILURE: "CREATE_TRACK_FAILURE"
}

export const TYPES_LOAD_TRACKS = {
  LOADING_TRACKS: "LOADING_TRACKS",
  LOAD_TRACKS_SUCCESS: "LOAD_TRACKS_SUCCESS",
  LOAD_TRACKS_FAILURE: "LOAD_TRACKS_FAILURE",
}
//#endregion

//#region ------- PLAYER --------
export const TYPES_CREATE_PLAYER = {
  CREATE_PLAYER: "CREATE_PLAYER",
  CREATE_PLAYER_SUCCESS: "CREATE_PLAYER_SUCCESS",
  CREATE_PLAYER_FAILURE: "CREATE_PLAYER_FAILURE",
}

export const TYPES_LOAD_PLAYERS = {
  LOADING_PLAYERS: "LOADING_PLAYERS",
  LOAD_PLAYERS_SUCCESS: "LOAD_PLAYERS_SUCCESS",
  LOAD_PLAYERS_FAILURE: "LOAD_PLAYERS_FAILURE",
}
//#endregion

//#region ------- CAR --------
export const TYPES_CREATE_CAR ={
    CREATE_CAR: "CREATE_CAR",
    CREATE_CAR_SUCCESS: "CREATE_CAR_SUCCESS",
    CREATE_CAR_FAILURE: "CREATE_CAR_FAILURE",
}

export const TYPES_LOAD_CARS = {
  LOADING_CARS: "LOADING_CARS",
  LOAD_CARS_SUCCESS: "LOAD_CARS_SUCCESS",
  LOAD_CARS_FAILURE: "LOAD_CARS_FAILURE",
}
//#endregion

//#region ------- game --------
export const TYPES_CREATE_GAME = {
  CREATE_GAME: "CREATE_GAME",
  CREATE_GAME_SUCCESS: "CREATE_GAME_SUCCESS",
  CREATE_GAME_FAILURE: "CREATE_GAME_FAILURE",
}

export const TYPES_LOAD_GAME = {
  LOADING_GAMES: "LOADING_GAME",
  LOAD_GAME_SUCCESS: "LOAD_GAMES_SUCCESS",
  LOAD_GAME_FAILURE: "LOAD_GAMES_FAILURE",
}
//#endregion

//#region ------- RAIL --------
export const TYPES_CREATE_LANE = {
  CREATE_LANE: "CREATE_LANE",
  CREATE_LANE_SUCCESS: "CREATE_LANE_SUCCESS",
  CREATE_LANE_FAILURE: "CREATE_LANE_FAILURE",
}

export const TYPES_LOAD_LANE = {
  LOADING_LANE: "LOADING_LANE",
  LOAD_LANE_SUCCESS: "LOAD_LANE_SUCCESS",
  LOAD_LANE_FAILURE: "LOAD_LANE_FAILURE",
}
//#endregion

//#region ------- RAIL --------
export const TYPES_CREATE_PODIUM = {
  CREATE_PODIUM: "CREATE_PODIUM",
  CREATE_PODIUM_SUCCESS: "CREATE_PODIUM_SUCCESS",
  CREATE_PODIUM_FAILURE: "CREATE_PODIUM_FAILURE",
}

export const TYPES_LOAD_PODIUM = {
  LOADING_PODIUM: "LOADING_PODIUM",
  LOAD_PODIUM_SUCCESS: "LOAD_PODIUM_SUCCESS",
  LOAD_PODIUM_FAILURE: "LOAD_PODIUM_FAILURE",
}
//#endregion